#!/usr/bin/env php
<?php

/*
 * This file is part of PHPLOC.
 *
 * (c) Sebastian Bergmann <sebastian@phpunit.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
use Hertel\PhpLoc\Analyser;
use Hertel\PhpLoc\Formatter\JsonResultFormatter;
use Hertel\PhpLoc\Formatter\TextResultFormatter;
use SebastianBergmann\FileIterator\Facade;
use SebastianBergmann\Version;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;

if (!class_exists(Analyser::class)) {
    $loaded = false;

    foreach ([__DIR__.'/../../autoload.php', __DIR__.'/vendor/autoload.php'] as $file) {
        if (file_exists($file)) {
            require $file;

            $loaded = true;

            break;
        }
    }

    if (!$loaded) {
        fwrite(
            \STDERR,
            'You need to set up the project dependencies using the following commands:'.\PHP_EOL.
            'wget https://getcomposer.org/composer.phar'.\PHP_EOL.
            'php composer.phar install'.\PHP_EOL,
        );

        exit(1);
    }
}

$version = (new Version('8.0', __DIR__))->asString();

(new SingleCommandApplication())
    ->setName('phploc')
    ->setVersion($version)
    ->addArgument(
        'directory',
        InputArgument::REQUIRED | InputArgument::IS_ARRAY,
        'Directory to analyse',
    )
    ->addOption(
        'json',
        null,
        InputOption::VALUE_NONE,
        'Print the result as JSON instead of as text',
    )
    ->setCode(
        static function (InputInterface $input, OutputInterface $output) use ($version): int {
            $json = (bool) $input->getOption('json');

            // The banner would make the output invalid JSON.
            if (!$json) {
                $output->writeln(sprintf('phploc %s by Sebastian Bergmann.', $version));
                $output->writeln('');
            }

            $files = (new Facade())->getFilesAsArray($input->getArgument('directory'), '.php');

            if ([] === $files) {
                $output->writeln('No files found to scan');

                return Command::FAILURE;
            }

            $result = (new Analyser())->analyse($files);

            $output->write(
                $json ? (new JsonResultFormatter())->format($result) : (new TextResultFormatter())->format($result),
            );

            return Command::SUCCESS;
        },
    )
    ->run();
